export enum SupplierCategory {
  ELECTRONICS = "ELECTRONICS",
  COMPUTERS = "COMPUTERS",
  NETWORKING = "NETWORKING",
  OFFICE_SUPPLIES = "OFFICE_SUPPLIES",
  FURNITURE = "FURNITURE",
  HARDWARE = "HARDWARE",
  PACKAGING = "PACKAGING",
  INDUSTRIAL = "INDUSTRIAL",
  CLEANING = "CLEANING",
  OTHER = "OTHER"
}

export enum SupplierStatus {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE"
}